# -*- coding: utf-8 -*-
"""senhaSegura_Python.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Aur-6_JB4uzPfkARqPGck_qWTCzULVD6
"""

!pip install gradio --quiet

import re
import gradio as gr

def verificar_senha(senha):
  if len(senha) < 8:
    return "Senha muito curta. A senha deve ter, no mínimo, 8 caracteres."
  if not re.search(r"[A-Z]", senha):
    return "A senha deve ter pelo menos 1 letra maiúscula."
  if not re.search(r"[a-z]", senha):
    return "A senha deve ter pelo menos 1 letra minúscula."
  if not re.search(r"[0-9]", senha):
    return "A senha deve ter pelo menos 1 caracter numérico."
  if not re.search(r"[!@#$%&*()_\-+=|\\{}\[\]/']",senha):
    return "A senha deve ter pelo menos 1 caracter especial."
  return "Senha aprovada!"

tela = gr.Interface(
    fn=verificar_senha,
    inputs=gr.Textbox(label="Digite sua senha: "),
    outputs=gr.Textbox(label="Resultado da verificação de senha:"),
    title="Verificador de Senhas",
    description="Verifique se sua senha atende aos critérios mínimos de segurança.",
    allow_flagging="never",
    submit_btn="Checar senha",
    clear_btn="Limpar entrada"
)

tela.launch()